# Generated by Django 3.2.25 on 2025-10-16 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_registereduser_reset_token_reset_token_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks_multiple', to=settings.AUTH_USER_MODEL),
        ),
    ]
