# Generated by Django 3.2.25 on 2025-11-15 15:10

import core.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user.user_profile_photo_path),
        ),
    ]
