# Generated by Django 3.2.25 on 2025-11-25 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_registereduser_profile_photo'),
        ('core', '0005_reports_and_enhanced_reviews'),
    ]

    operations = [
    ]
