# Generated by Django migration for UserFollows model

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20251125_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(
                    help_text='The user who is following',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='following_set',
                    to=settings.AUTH_USER_MODEL
                )),
                ('following', models.ForeignKey(
                    help_text='The user being followed',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='followers_set',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name_plural': 'User follows',
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
