# Generated by Django 3.2.25 on 2025-12-12 05:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userfollows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('NEIGHBORHOOD_HERO', 'Neighborhood Hero'), ('JACK_OF_ALL_TRADES', 'Jack of All Trades'), ('SELECTED_VOLUNTEER', 'Selected Volunteer'), ('CARING_CONTRIBUTOR', 'Caring Contributor'), ('HELP_AND_TRAVEL', 'Help & Travel'), ('RAPID_RESPONDER', 'Rapid Responder'), ('THE_UNSUNG_HERO', 'The Unsung Hero'), ('THE_LIFESAVER', 'The Lifesaver'), ('NIGHT_OWL', 'Night Owl'), ('THE_HOLIDAY_HERO', 'The Holiday Hero'), ('JUST_PERFECT', 'Just Perfect'), ('RISING_HELPER', 'Rising Helper'), ('GENTLE_COMMUNICATOR', 'Gentle Communicator'), ('MODEL_CITIZEN', 'Model Citizen'), ('RELIABLE_NEIGHBOUR', 'Reliable Neighbour'), ('PEOPLE_TRUST_YOU', 'People Trust You'), ('PLATE_NOT_EMPTY', 'Plate is Not Sent Back Empty'), ('FAR_SIGHTED', 'Far Sighted'), ('FULL_GALLERY', 'Full Gallery')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.FloatField(default=0.0, help_text='Overall average score (calculated automatically)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='core.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
