# Generated by Django 3.2.25 on 2025-12-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20251212_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('NEIGHBORHOOD_HERO', 'Neighborhood Hero'), ('JACK_OF_ALL_TRADES', 'Jack of All Trades'), ('SELECTED_VOLUNTEER', 'Selected Volunteer'), ('CARING_CONTRIBUTOR', 'Caring Contributor'), ('HELP_AND_TRAVEL', 'Help & Travel'), ('RAPID_RESPONDER', 'Rapid Responder'), ('THE_UNSUNG_HERO', 'The Unsung Hero'), ('THE_LIFESAVER', 'The Lifesaver'), ('NIGHT_OWL', 'Night Owl'), ('THE_HOLIDAY_HERO', 'The Holiday Hero'), ('JUST_PERFECT', 'Just Perfect'), ('RISING_HELPER', 'Rising Helper'), ('GENTLE_COMMUNICATOR', 'Gentle Communicator'), ('MODEL_CITIZEN', 'Model Citizen'), ('RELIABLE_NEIGHBOUR', 'Reliable Neighbour'), ('PEOPLE_TRUST_YOU', 'People Trust You'), ('PLATE_NOT_EMPTY', 'Plate is Not Sent Back Empty'), ('FAR_SIGHTED', 'Far Sighted'), ('FULL_GALLERY', 'Full Gallery'), ('THE_ICEBREAKER', 'The Icebreaker')], max_length=50, unique=True),
        ),
    ]
