# Generated by Django 3.2.25 on 2025-12-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_badge_badge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('VOLUNTEER_APPLIED', 'Volunteer Applied'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_CANCELLED', 'Task Cancelled'), ('NEW_REVIEW', 'New Review'), ('BADGE_EARNED', 'Badge Earned'), ('SYSTEM_NOTIFICATION', 'System Notification')], default='SYSTEM_NOTIFICATION', max_length=30),
        ),
    ]
