<<<<<<< HEAD
const tintColorLight = '#3559F7';
const tintColorDark = '#8AA5FF';
const tintColorHighContrast = '#00FFFF';

export type ThemeName = 'light' | 'dark' | 'highContrast';

type ThemeScale = {
  text: string;
  textMuted: string;
  background: string;
  tint: string;
  icon: string;
  tabIconDefault: string;
  tabIconSelected: string;
  primary: string;
  secondary: string;
  accent: string;
  gray: string;
  lightGray: string;
  darkGray: string;
  pink: string;
  lightPink: string;
  purple: string;
  lightPurple: string;
  card: string;
  cardUnread: string;
  border: string;
  error: string;
  statusHighBackground: string;
  statusHighText: string;
  statusMediumBackground: string;
  statusMediumText: string;
  statusLowBackground: string;
  statusLowText: string;
  statusCompletedBackground: string;
  statusCompletedText: string;
  statusCancelledBackground: string;
  statusCancelledText: string;
  statusExpiredBackground: string;
  statusExpiredText: string;
  statusAssignedBackground: string;
  statusAssignedText: string;
  statusInProgressBackground: string;
  statusInProgressText: string;
  statusPostedBackground: string;
  statusPostedText: string;
  statusGenericBackground: string;
  statusGenericText: string;
  statusPastBackground: string;
  statusPastText: string;
  statusPastBorder: string;
  urgencyHighBackground: string;
  urgencyHighText: string;
  urgencyMediumBackground: string;
  urgencyMediumText: string;
  urgencyLowBackground: string;
  urgencyLowText: string;
  labelDefaultBackground: string;
  labelDefaultText: string;
  labelDefaultBorder: string;
  onPrimary: string;
  onSecondary: string;
  onAccent: string;
  focusRing: string;
  focusRingInner: string;
  pressedBackground: string;
  pressedBorder: string;
  inputBackground: string;
  inputPlaceholder: string;
  overlay: string;
};

const palette: Record<ThemeName, ThemeScale> = {
  light: {
    text: '#0F172A',
    textMuted: '#475467',
    background: '#FFFFFF',
    tint: tintColorLight,
    icon: '#475467',
    tabIconDefault: '#9AA3B2',
    tabIconSelected: tintColorLight,
    primary: '#3559F7',
    secondary: '#0F8EC7',
    accent: '#0FA968',
    gray: '#F4F6FA',
    lightGray: '#F8FAFC',
    darkGray: '#0F172A',
    pink: '#B3206B',
    lightPink: '#FFE4F2',
    purple: '#5F2EEA',
    lightPurple: '#EEF2FF',
    card: '#FDFDFE',
    cardUnread: '#EEF2FF',
    border: '#E4E7EC',
    error: '#C81E1E',
    statusHighBackground: '#FEE2E2',
    statusHighText: '#7F1D1D',
    statusMediumBackground: '#FEF3C7',
    statusMediumText: '#92400E',
    statusLowBackground: '#DCFCE7',
    statusLowText: '#166534',
    statusCompletedBackground: '#E0F2FE',
    statusCompletedText: '#0F5096',
    statusCancelledBackground: '#F8F9FC',
    statusCancelledText: '#475467',
    statusExpiredBackground: '#F4F5F7',
    statusExpiredText: '#1F2937',
    statusAssignedBackground: '#E0F2FE',
    statusAssignedText: '#0B63C6',
    statusInProgressBackground: '#FEF3C7',
    statusInProgressText: '#B45309',
    statusPostedBackground: '#E4ECFF',
    statusPostedText: '#1C3FAA',
    statusGenericBackground: '#F2F4F7',
    statusGenericText: '#1D2939',
    statusPastBackground: '#F3F4F6',
    statusPastText: '#4B5563',
    statusPastBorder: '#E4E7EC',
    urgencyHighBackground: '#FEE4E2',
    urgencyHighText: '#B42318',
    urgencyMediumBackground: '#FEF0C7',
    urgencyMediumText: '#B54708',
    urgencyLowBackground: '#E2F6ED',
    urgencyLowText: '#027A48',
    labelDefaultBackground: '#E4E7EC',
    labelDefaultText: '#111322',
    labelDefaultBorder: '#CBD5F5',
    onPrimary: '#FFFFFF',
    onSecondary: '#FFFFFF',
    onAccent: '#FFFFFF',
    focusRing: '#111827',
    focusRingInner: '#FFFFFF',
    pressedBackground: '#E0EAFF',
    pressedBorder: '#3559F7',
    inputBackground: '#FFFFFF',
    inputPlaceholder: '#94A3B8',
    overlay: 'rgba(15,23,42,0.55)',
  },
  dark: {
    text: '#F4F6FB',
    textMuted: '#9EA7B8',
    background: '#050A12',
    tint: tintColorDark,
    icon: '#A1AFC6',
    tabIconDefault: '#5C6A82',
    tabIconSelected: tintColorDark,
    primary: '#8AA5FF',
    secondary: '#65CFF2',
    accent: '#5CE3B2',
    gray: '#101622',
    lightGray: '#0D121B',
    darkGray: '#F8FAFC',
    pink: '#EE91C0',
    lightPink: '#2A1723',
    purple: '#B39CFF',
    lightPurple: '#1E2237',
    card: '#0D1523',
    cardUnread: '#1A1F33',
    border: '#273248',
    error: '#F37C7C',
    statusHighBackground: '#3A1218',
    statusHighText: '#FECACA',
    statusMediumBackground: '#362712',
    statusMediumText: '#FBD38D',
    statusLowBackground: '#1C2B1F',
    statusLowText: '#A7F3D0',
    statusCompletedBackground: '#1A2536',
    statusCompletedText: '#B3E0FF',
    statusCancelledBackground: '#1F2437',
    statusCancelledText: '#C5CDE0',
    statusExpiredBackground: '#222932',
    statusExpiredText: '#B8C1D6',
    statusAssignedBackground: '#1A2A3D',
    statusAssignedText: '#A3E3FF',
    statusInProgressBackground: '#2F2411',
    statusInProgressText: '#F7B267',
    statusPostedBackground: '#202042',
    statusPostedText: '#B5C4FF',
    statusGenericBackground: '#1F2333',
    statusGenericText: '#C6D0E7',
    statusPastBackground: '#1C2231',
    statusPastText: '#A6B2CB',
    statusPastBorder: '#313B52',
    urgencyHighBackground: '#4D1A1F',
    urgencyHighText: '#FECACA',
    urgencyMediumBackground: '#3D2C12',
    urgencyMediumText: '#FFE6B3',
    urgencyLowBackground: '#1F2E22',
    urgencyLowText: '#ACF2D9',
    labelDefaultBackground: '#2A3245',
    labelDefaultText: '#F6F8FF',
    labelDefaultBorder: '#3A4560',
    onPrimary: '#050A12',
    onSecondary: '#050A12',
    onAccent: '#050A12',
    focusRing: '#C1D5FF',
    focusRingInner: '#0D1523',
    pressedBackground: '#1B2440',
    pressedBorder: '#8AA5FF',
    inputBackground: '#101A2A',
    inputPlaceholder: '#9CA3AF',
    overlay: 'rgba(5,10,18,0.76)',
  },
  highContrast: {
    text: '#FFFFFF',
    textMuted: '#F5F5F5',
    background: '#000000',
    tint: tintColorHighContrast,
    icon: '#F5F5F5',
    tabIconDefault: '#B3B3B3',
    tabIconSelected: tintColorHighContrast,
    primary: '#00FFFF',
    secondary: '#FFE800',
    accent: '#00FF85',
    gray: '#0F0F0F',
    lightGray: '#141414',
    darkGray: '#FFFFFF',
    pink: '#FF4FD8',
    lightPink: '#2B0031',
    purple: '#A26BFF',
    lightPurple: '#1A0033',
    card: '#000000',
    cardUnread: '#141414',
    border: '#FFFFFF',
    error: '#FF4B4B',
    statusHighBackground: '#000000',
    statusHighText: '#FF9DAF',
    statusMediumBackground: '#000000',
    statusMediumText: '#FFE066',
    statusLowBackground: '#000000',
    statusLowText: '#78FFB3',
    statusCompletedBackground: '#000000',
    statusCompletedText: '#9AD9FF',
    statusCancelledBackground: '#000000',
    statusCancelledText: '#E6E6E6',
    statusExpiredBackground: '#000000',
    statusExpiredText: '#F5F5F5',
    statusAssignedBackground: '#000000',
    statusAssignedText: '#AEEDFF',
    statusInProgressBackground: '#000000',
    statusInProgressText: '#FFED8A',
    statusPostedBackground: '#000000',
    statusPostedText: '#C4B5FF',
    statusGenericBackground: '#000000',
    statusGenericText: '#FFFFFF',
    statusPastBackground: '#000000',
    statusPastText: '#FFFFFF',
    statusPastBorder: '#FFFFFF',
    urgencyHighBackground: '#000000',
    urgencyHighText: '#FF9DAF',
    urgencyMediumBackground: '#000000',
    urgencyMediumText: '#FFE066',
    urgencyLowBackground: '#000000',
    urgencyLowText: '#78FFB3',
    labelDefaultBackground: '#000000',
    labelDefaultText: '#FFFFFF',
    labelDefaultBorder: '#FFFFFF',
    onPrimary: '#000000',
    onSecondary: '#000000',
    onAccent: '#000000',
    focusRing: '#FFFFFF',
    focusRingInner: '#000000',
    pressedBackground: '#1A1A1A',
    pressedBorder: '#FFFFFF',
    inputBackground: '#000000',
    inputPlaceholder: '#E6E6E6',
    overlay: 'rgba(255,255,255,0.25)',
  },
};

export type ThemeTokens = typeof palette.light;

export const Colors: Record<ThemeName, ThemeTokens> = palette;
=======
const tintColorLight = '#0a7ea4';
const tintColorDark = '#fff';
const tintColorHighContrast = '#FFD400';

const lightPalette = {
  text: '#11181C',
  textMuted: '#687076',
  background: '#fff',
  tint: tintColorLight,
  icon: '#687076',
  tabIconDefault: '#687076',
  tabIconSelected: tintColorLight,
  primary: '#6C63FF',
  secondary: '#FF6584',
  accent: '#4CAF50',
  gray: '#f0f0f0',
  lightGray: '#f9f9f9',
  darkGray: '#333',
  pink: '#e8618c',
  lightPink: '#FFD1DC',
  purple: '#E6E6FA',
  lightPurple: '#F3F2FF',
  card: '#FFFFFF',
  cardUnread: '#F3F2FF',
  border: '#E0E0E0',
  error: '#D32F2F',
  statusHighBackground: '#FFEBEE',
  statusHighText: '#D32F2F',
  statusMediumBackground: '#FFF8E1',
  statusMediumText: '#FFA000',
  statusLowBackground: '#E8F5E9',
  statusLowText: '#388E3C',
  statusCompletedBackground: '#E3F2FD',
  statusCompletedText: '#1976D2',
  statusCancelledBackground: '#F5F5F5',
  statusCancelledText: '#757575',
  statusExpiredBackground: '#ECEFF1',
  statusExpiredText: '#546E7A',
  statusAssignedBackground: '#E1F5FE',
  statusAssignedText: '#0288D1',
  statusInProgressBackground: '#FFF3E0',
  statusInProgressText: '#F57C00',
  statusPostedBackground: '#E8EAF6',
  statusPostedText: '#3949AB',
  statusGenericBackground: '#F5F5F5',
  statusGenericText: '#757575',
  statusPastBackground: '#F5F5F5',
  statusPastText: '#757575',
  statusPastBorder: '#E0E0E0',
  urgencyHighBackground: '#FFCDD2',
  urgencyHighText: '#D32F2F',
  urgencyMediumBackground: '#FFE0B2',
  urgencyMediumText: '#F57C00',
  urgencyLowBackground: '#C8E6C9',
  urgencyLowText: '#388E3C',
  labelDefaultBackground: '#E0E0E0',
  labelDefaultText: '#333333',
  labelDefaultBorder: '#E0E0E0',
} as const;

type Palette = typeof lightPalette;

const darkPalette: Palette = {
  text: '#ECEDEE',
  textMuted: '#9A9FA5',
  background: '#121212',
  tint: tintColorDark,
  icon: '#9BA1A6',
  tabIconDefault: '#9BA1A6',
  tabIconSelected: tintColorDark,
  primary: '#7F77FF',
  secondary: '#FF87A1',
  accent: '#66BB6A',
  gray: '#2c2c2e',
  lightGray: '#1c1c1e',
  darkGray: '#eaeaea',
  pink: '#e8618c',
  lightPink: '#FFD1DC',
  purple: '#5A5499',
  lightPurple: '#2A284D',
  card: '#1E1E1E',
  cardUnread: '#2A284D',
  border: '#3A3A3C',
  error: '#EF5350',
  statusHighBackground: '#4E3436',
  statusHighText: '#FF8A80',
  statusMediumBackground: '#544B3E',
  statusMediumText: '#FFD180',
  statusLowBackground: '#3E4B3F',
  statusLowText: '#A5D6A7',
  statusCompletedBackground: '#3A4C5A',
  statusCompletedText: '#82B1FF',
  statusCancelledBackground: '#424242',
  statusCancelledText: '#BDBDBD',
  statusExpiredBackground: '#424547',
  statusExpiredText: '#B0BEC5',
  statusAssignedBackground: '#364F5A',
  statusAssignedText: '#80D8FF',
  statusInProgressBackground: '#544A3E',
  statusInProgressText: '#FFAB40',
  statusPostedBackground: '#3F4358',
  statusPostedText: '#9FA8DA',
  statusGenericBackground: '#424242',
  statusGenericText: '#BDBDBD',
  statusPastBackground: '#424242',
  statusPastText: '#BDBDBD',
  statusPastBorder: '#3A3A3C',
  urgencyHighBackground: '#D32F2F',
  urgencyHighText: '#FFCDD2',
  urgencyMediumBackground: '#F57C00',
  urgencyMediumText: '#FFE0B2',
  urgencyLowBackground: '#388E3C',
  urgencyLowText: '#C8E6C9',
  labelDefaultBackground: '#383838',
  labelDefaultText: '#F5F5F5',
  labelDefaultBorder: '#3A3A3C',
} as const;

const highContrastPalette: Palette = {
  ...darkPalette,
  text: '#FFFFFF',
  textMuted: '#E0E0E0',
  background: '#000000',
  tint: tintColorHighContrast,
  icon: '#FFFFFF',
  tabIconDefault: '#BFBFBF',
  tabIconSelected: tintColorHighContrast,
  primary: tintColorHighContrast,
  secondary: '#FF5C8D',
  accent: '#78FFB3',
  gray: '#101010',
  lightGray: '#050505',
  darkGray: '#FFFFFF',
  pink: '#FF5C8D',
  lightPink: '#4B1026',
  purple: '#B084FF',
  lightPurple: '#2D1B4E',
  card: '#050505',
  cardUnread: '#111111',
  border: '#393939',
  error: '#FF6B6B',
  statusHighBackground: '#4C0000',
  statusHighText: '#FFC1C1',
  statusMediumBackground: '#4A3500',
  statusMediumText: '#FFD966',
  statusLowBackground: '#003B18',
  statusLowText: '#96FFB8',
  statusCompletedBackground: '#002D4C',
  statusCompletedText: '#A9DFFF',
  statusCancelledBackground: '#1F1F1F',
  statusCancelledText: '#E6E6E6',
  statusExpiredBackground: '#1E1E1E',
  statusExpiredText: '#F0F0F0',
  statusAssignedBackground: '#00344C',
  statusAssignedText: '#9EEBFF',
  statusInProgressBackground: '#4A2A00',
  statusInProgressText: '#FFDE8D',
  statusPostedBackground: '#1F0F3D',
  statusPostedText: '#E2D0FF',
  statusGenericBackground: '#1A1A1A',
  statusGenericText: '#E6E6E6',
  statusPastBackground: '#1A1A1A',
  statusPastText: '#E6E6E6',
  statusPastBorder: '#4D4D4D',
  urgencyHighBackground: '#800000',
  urgencyHighText: '#FFD6D6',
  urgencyMediumBackground: '#664400',
  urgencyMediumText: '#FFE08A',
  urgencyLowBackground: '#004221',
  urgencyLowText: '#9BFFB0',
  labelDefaultBackground: '#1F1F1F',
  labelDefaultText: '#FFFFFF',
  labelDefaultBorder: '#4D4D4D',
} as const;

export const Colors = {
  light: lightPalette,
  dark: darkPalette,
  highContrast: highContrastPalette,
} as const;

export type ThemeName = keyof typeof Colors;
export type ThemeColors = (typeof Colors)[ThemeName];
>>>>>>> 7bdd68a (Add dark mode and high-contrast feature)
